# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: 
    - MSBuild
    - Nuget


stages:
  - stage: Pre_Build
    jobs:
      - job: set_vars
        steps:
          - script: echo $(Agent.System.Capabilities) 
          - script: echo $(Agent.Name)
          - task: Bash@3
            inputs:
              filePath: $(Build.SourcesDirectory)\scripts\ss.sh

  - stage: build
    jobs:
      - job: build
        steps:
          - task: MSBuild@1
            inputs:
              solution: '**/*.sln'
              msbuildVersion: '15.0'
              msbuildArchitecture: 'x64'
              restoreNugetPackages: true     


