# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: 
    - MSBuild
    - Nuget

# resources:
#   repositories:
#     - repository: local repo
#       type: git
#       ref: refs/heads/master
#       endpoint: C:\Users\abhishek.chaudhary\Documents\All Repos\salescloser360


variables:
  ExeNamePrefix: Bamboo_
  MajorVersion: 1
  MinorVersion: 1
  NAS: \\10.91.1.12
  NAS_Path: 'N:'
  Parent_local_repo: \"/mnt/c/Users/abhishek.chaudhary/Documents/All Repos/salescloser360\"
  TargetPath: $(NAS)\Data\Builds\Sales Closer\
  REPO_ROOT_VAR: $(Build.SourcesDirectory)\Source\Sales_Closer_360
  Source_code_path: $(REPO_ROOT_VAR)\Source #contain .sln
  Product_version: 1.0.0.390
  SCLIB_PATH: $(REPO_ROOT_VAR)\Libraries
  Smart_Assembly_Path_dir: \"C:\\Program Files\\Red Gate\\SmartAssembly 7\\SmartAssembly.com\"

stages:
  - stage: SC_Checkout
    jobs:
      - job: Clone_form_Local
        steps:
          - task: Bash@3
            inputs:
              filePath: $(Build.SourcesDirectory)\scripts\clone_repo.sh #cloned dir = ./sc
            env:
              repo_to_clone: $(Parent_local_repo)
  # - stage: Pre_Build
  #   jobs:
  #     - job: set_vars
  #       steps:
  #         # - checkout: none
  #         # - script: echo $(Build.BinariesDirectory) 
  #         # - script: echo $(Agent.Name)
  #         - task: Bash@3
  #           inputs:
  #             filePath: $(Build.SourcesDirectory)\scripts\setVariables.sh

  # - stage: Compile_SC360
  #   dependsOn: SC_Checkout
  #   jobs:
  #     - job: Restore_Packages_and_Build
  #       steps:
  #         - checkout: none
  #         - task: MSBuild@1
  #           inputs:
  #             solution: $(Source_code_path)/*.sln
  #             msbuildArguments: -p:Configuration="Release" -p:Platform=x64 -t:Rebuild -r

  #     - job: Update_Version
  #       dependsOn: Restore_Packages_and_Build
  #       steps:
  #         - checkout: none
  #         - task: CmdLine@2
  #           inputs:
  #             workingDirectory: $(Source_code_path)/MainWindow/bin/Release
  #             script: verpatch.exe SalesCloser360.exe $(Product_version) /pv $(Product_version)

  # - stage: Run_Smart_Assembly
  #   dependsOn: Compile_SC360
  #   jobs:
  #     - job: Build_Smart_Assembly_project
  #       steps:
  #         - checkout: none
  #         - bash: cmd.exe /k $(Smart_Assembly_Path_dir) SalesCloser360.saproj
  #           workingDirectory: $(REPO_ROOT_VAR)/Build/SmartAssembly