# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: 
    - MSBuild
    - Nuget

# resources:
#   repositories:
#     - repository: local repo
#       type: git



stages:
  - stage: Pre_Build
    jobs:
      - job: set_vars
        steps:
          - checkout: none
          - script: echo $(Build.BinariesDirectory) 
          - script: echo $(Agent.Name)
          - task: Bash@3
            inputs:
              filePath: $(Build.SourcesDirectory)\scripts\ss.sh

  - stage: Build
    jobs:
      - job: Restore_NUG_PCKS
        steps:
          - checkout: none
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              feedsToUse: 'config'
              nugetConfigPath: 'nuget.config'   


